[package]
name = "procfill"
version = "0.2.0"
edition = "2021"

[dependencies]
log = "0.4.22"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
anyhow = "1.0"
chrono = "0.4"
libc = "0.2"


[dev-dependencies]
tempfile = "3.8" 